all:code clean


code:01-outputPID 02-outputIDs 09-fanwait 10-showreturnstatus

01-outputPID:01-outputPID.o
	cc -o 01-outputPID 01-outputPID.o
01-outputPID.o:01-outputPID.c
	cc -c 01-outputPID.c

02-outputIDs:02-outputIDs.o
	cc -o 02-outputIDs 02-outputIDs.o
02-outputIDs.o:02-outputIDs.c
	cc -c 02-outputIDs.c


09-fanwait:09-fanwait.o
	cc -o 09-fanwait 09-fanwait.o
09-fanwait.o:09-fanwait.c
	cc -c 09-fanwait.c

10-showreturnstatus:10-showreturnstatus.o
	cc -o 10-showreturnstatus 10-showreturnstatus.o
10-showreturnstatus.o:10-showreturnstatus.c
	cc -c 10-showreturnstatus.c

























clean:
	rm *o
