all:code clean

code:\
01-read\
03-readwrite
	


01-read:01-read.o
	cc -o 01-read 01-read.o
01-read.o:01-read.c
	cc -c 01-read.c

03-readwrite:03-readwrite.o
	cc -o 03-readwrite 03-readwrite.o
03-readwrite.o:03-readwrite.c
	cc -c 03-readwrite.c












clean:
	rm *o
