all:code clean
code:01-getcwdpathmax

01-getcwdpathmax:01-getcwdpathmax.o
	cc -o 01-getcwdpathmax 01-getcwdpathmax.o
01-getcwdpathmax.o:01-getcwdpathmax.c
	cc -c 01-getcwdpathmax.c


















clean:
	rm *.o
